### ISSUE TITLE
Finish quicker

### ISSUE THREAD

**Issue by RubeRad** [RubeRad/MarcoMD#16]
Right now, when you complete the erasure that eliminates the last baterium, it waits for any extra pieces to fall, and generates the new unguent before ending.

Detect ending immediately and avoid those unnecessary steps.

Google 'pygame text' and print a happy message

(While you're at it, if the player loses, instead of printing "Kablooey" to the console, print a sad message to the game screen)

**Comment by GitMason** [comment]
Closed by pr #21
